env:
- TRAVIS_BUILD_NUMBER++
dist: xenial
language: cpp
compiler: gcc
addons:
  apt:
    packages:
    - libboost-test-dev
    - libspdlog-dev
script:
- cmake . 
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T chaplin-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ulibertejunior:$BINTRAY_API_KEY "https://api.bintray.com/content/libertejunior/potuc-cpp/homework/$TRAVIS_BUILD_NUMBER/chaplin-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
